### ISSUE TITLE
[BUG]  Issue with Clear Invites

### ISSUE THREAD

**Issue by elijahrode** [LolRiTTeR/invite-manager-bot#3]
**Describe the bug**
The !ping command crashes the bot

**Steps to reproduce**
!clearInvites returns with this:
There was an error executing the command. Please report this to a developer:
Column 'clearedAmount' cannot be null

**Comment by SemiMute** [comment]
Hello,
I was unable to reproduce this bug. Please re-open a ticket if this is still persisting with more information regarding the issue.
